services:
  db:
    image: postgres:16
    container_name: learnify-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: learnify
    ports:
      - "5433:5432"
    volumes:
      - learnify_db:/var/lib/postgresql/data

volumes:
  learnify_db:
